// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cameraMsgs.proto

package cameraMsgs;

public final class CameraMsgs {
  private CameraMsgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum systemStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    CAMERA_DOWN(0, 0),
    CAMERA_READY(1, 1),
    CAMERA_OPERATIONAL(2, 2),
    CAMERA_ERROR(3, 3),
    CAMERA_FAILED(4, 4),
    UNKNOWN(5, 5),
    ;
    
    public static final int CAMERA_DOWN_VALUE = 0;
    public static final int CAMERA_READY_VALUE = 1;
    public static final int CAMERA_OPERATIONAL_VALUE = 2;
    public static final int CAMERA_ERROR_VALUE = 3;
    public static final int CAMERA_FAILED_VALUE = 4;
    public static final int UNKNOWN_VALUE = 5;
    
    
    public final int getNumber() { return value; }
    
    public static systemStatus valueOf(int value) {
      switch (value) {
        case 0: return CAMERA_DOWN;
        case 1: return CAMERA_READY;
        case 2: return CAMERA_OPERATIONAL;
        case 3: return CAMERA_ERROR;
        case 4: return CAMERA_FAILED;
        case 5: return UNKNOWN;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<systemStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<systemStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<systemStatus>() {
            public systemStatus findValueByNumber(int number) {
              return systemStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cameraMsgs.CameraMsgs.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final systemStatus[] VALUES = {
      CAMERA_DOWN, CAMERA_READY, CAMERA_OPERATIONAL, CAMERA_ERROR, CAMERA_FAILED, UNKNOWN, 
    };
    
    public static systemStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private systemStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:cameraMsgs.systemStatus)
  }
  
  public interface cameraStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
    boolean hasStatus();
    cameraMsgs.CameraMsgs.systemStatus getStatus();
    
    // optional bool laserOn = 3;
    boolean hasLaserOn();
    boolean getLaserOn();
    
    // optional string text = 4;
    boolean hasText();
    String getText();
  }
  public static final class cameraStatus extends
      com.google.protobuf.GeneratedMessage
      implements cameraStatusOrBuilder {
    // Use cameraStatus.newBuilder() to construct.
    private cameraStatus(Builder builder) {
      super(builder);
    }
    private cameraStatus(boolean noInit) {}
    
    private static final cameraStatus defaultInstance;
    public static cameraStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public cameraStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraStatus_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
    public static final int STATUS_FIELD_NUMBER = 2;
    private cameraMsgs.CameraMsgs.systemStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public cameraMsgs.CameraMsgs.systemStatus getStatus() {
      return status_;
    }
    
    // optional bool laserOn = 3;
    public static final int LASERON_FIELD_NUMBER = 3;
    private boolean laserOn_;
    public boolean hasLaserOn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getLaserOn() {
      return laserOn_;
    }
    
    // optional string text = 4;
    public static final int TEXT_FIELD_NUMBER = 4;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      time_ = 0L;
      status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
      laserOn_ = false;
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, laserOn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, laserOn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cameraMsgs.CameraMsgs.cameraStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cameraMsgs.CameraMsgs.cameraStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraStatus_fieldAccessorTable;
      }
      
      // Construct using cameraMsgs.CameraMsgs.cameraStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        laserOn_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cameraMsgs.CameraMsgs.cameraStatus.getDescriptor();
      }
      
      public cameraMsgs.CameraMsgs.cameraStatus getDefaultInstanceForType() {
        return cameraMsgs.CameraMsgs.cameraStatus.getDefaultInstance();
      }
      
      public cameraMsgs.CameraMsgs.cameraStatus build() {
        cameraMsgs.CameraMsgs.cameraStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cameraMsgs.CameraMsgs.cameraStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cameraMsgs.CameraMsgs.cameraStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cameraMsgs.CameraMsgs.cameraStatus buildPartial() {
        cameraMsgs.CameraMsgs.cameraStatus result = new cameraMsgs.CameraMsgs.cameraStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.laserOn_ = laserOn_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cameraMsgs.CameraMsgs.cameraStatus) {
          return mergeFrom((cameraMsgs.CameraMsgs.cameraStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cameraMsgs.CameraMsgs.cameraStatus other) {
        if (other == cameraMsgs.CameraMsgs.cameraStatus.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasLaserOn()) {
          setLaserOn(other.getLaserOn());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cameraMsgs.CameraMsgs.systemStatus value = cameraMsgs.CameraMsgs.systemStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              laserOn_ = input.readBool();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
      private cameraMsgs.CameraMsgs.systemStatus status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public cameraMsgs.CameraMsgs.systemStatus getStatus() {
        return status_;
      }
      public Builder setStatus(cameraMsgs.CameraMsgs.systemStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
        onChanged();
        return this;
      }
      
      // optional bool laserOn = 3;
      private boolean laserOn_ ;
      public boolean hasLaserOn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getLaserOn() {
        return laserOn_;
      }
      public Builder setLaserOn(boolean value) {
        bitField0_ |= 0x00000004;
        laserOn_ = value;
        onChanged();
        return this;
      }
      public Builder clearLaserOn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        laserOn_ = false;
        onChanged();
        return this;
      }
      
      // optional string text = 4;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:cameraMsgs.cameraStatus)
    }
    
    static {
      defaultInstance = new cameraStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cameraMsgs.cameraStatus)
  }
  
  public interface trackOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional sint32 x = 1;
    boolean hasX();
    int getX();
    
    // optional sint32 y = 2;
    boolean hasY();
    int getY();
  }
  public static final class track extends
      com.google.protobuf.GeneratedMessage
      implements trackOrBuilder {
    // Use track.newBuilder() to construct.
    private track(Builder builder) {
      super(builder);
    }
    private track(boolean noInit) {}
    
    private static final track defaultInstance;
    public static track getDefaultInstance() {
      return defaultInstance;
    }
    
    public track getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_track_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_track_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional sint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // optional sint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cameraMsgs.CameraMsgs.track parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.track parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.track parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cameraMsgs.CameraMsgs.track prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cameraMsgs.CameraMsgs.trackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_track_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_track_fieldAccessorTable;
      }
      
      // Construct using cameraMsgs.CameraMsgs.track.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cameraMsgs.CameraMsgs.track.getDescriptor();
      }
      
      public cameraMsgs.CameraMsgs.track getDefaultInstanceForType() {
        return cameraMsgs.CameraMsgs.track.getDefaultInstance();
      }
      
      public cameraMsgs.CameraMsgs.track build() {
        cameraMsgs.CameraMsgs.track result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cameraMsgs.CameraMsgs.track buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cameraMsgs.CameraMsgs.track result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cameraMsgs.CameraMsgs.track buildPartial() {
        cameraMsgs.CameraMsgs.track result = new cameraMsgs.CameraMsgs.track(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cameraMsgs.CameraMsgs.track) {
          return mergeFrom((cameraMsgs.CameraMsgs.track)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cameraMsgs.CameraMsgs.track other) {
        if (other == cameraMsgs.CameraMsgs.track.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readSInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional sint32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cameraMsgs.track)
    }
    
    static {
      defaultInstance = new track(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cameraMsgs.track)
  }
  
  public interface cameraTracksOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
    boolean hasStatus();
    cameraMsgs.CameraMsgs.systemStatus getStatus();
    
    // repeated .cameraMsgs.track target = 3;
    java.util.List<cameraMsgs.CameraMsgs.track> 
        getTargetList();
    cameraMsgs.CameraMsgs.track getTarget(int index);
    int getTargetCount();
    java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
        getTargetOrBuilderList();
    cameraMsgs.CameraMsgs.trackOrBuilder getTargetOrBuilder(
        int index);
    
    // repeated .cameraMsgs.track laser = 4;
    java.util.List<cameraMsgs.CameraMsgs.track> 
        getLaserList();
    cameraMsgs.CameraMsgs.track getLaser(int index);
    int getLaserCount();
    java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
        getLaserOrBuilderList();
    cameraMsgs.CameraMsgs.trackOrBuilder getLaserOrBuilder(
        int index);
    
    // optional bool laserOn = 5;
    boolean hasLaserOn();
    boolean getLaserOn();
    
    // optional bool roverDetected = 6;
    boolean hasRoverDetected();
    boolean getRoverDetected();
  }
  public static final class cameraTracks extends
      com.google.protobuf.GeneratedMessage
      implements cameraTracksOrBuilder {
    // Use cameraTracks.newBuilder() to construct.
    private cameraTracks(Builder builder) {
      super(builder);
    }
    private cameraTracks(boolean noInit) {}
    
    private static final cameraTracks defaultInstance;
    public static cameraTracks getDefaultInstance() {
      return defaultInstance;
    }
    
    public cameraTracks getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraTracks_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraTracks_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
    public static final int STATUS_FIELD_NUMBER = 2;
    private cameraMsgs.CameraMsgs.systemStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public cameraMsgs.CameraMsgs.systemStatus getStatus() {
      return status_;
    }
    
    // repeated .cameraMsgs.track target = 3;
    public static final int TARGET_FIELD_NUMBER = 3;
    private java.util.List<cameraMsgs.CameraMsgs.track> target_;
    public java.util.List<cameraMsgs.CameraMsgs.track> getTargetList() {
      return target_;
    }
    public java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
        getTargetOrBuilderList() {
      return target_;
    }
    public int getTargetCount() {
      return target_.size();
    }
    public cameraMsgs.CameraMsgs.track getTarget(int index) {
      return target_.get(index);
    }
    public cameraMsgs.CameraMsgs.trackOrBuilder getTargetOrBuilder(
        int index) {
      return target_.get(index);
    }
    
    // repeated .cameraMsgs.track laser = 4;
    public static final int LASER_FIELD_NUMBER = 4;
    private java.util.List<cameraMsgs.CameraMsgs.track> laser_;
    public java.util.List<cameraMsgs.CameraMsgs.track> getLaserList() {
      return laser_;
    }
    public java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
        getLaserOrBuilderList() {
      return laser_;
    }
    public int getLaserCount() {
      return laser_.size();
    }
    public cameraMsgs.CameraMsgs.track getLaser(int index) {
      return laser_.get(index);
    }
    public cameraMsgs.CameraMsgs.trackOrBuilder getLaserOrBuilder(
        int index) {
      return laser_.get(index);
    }
    
    // optional bool laserOn = 5;
    public static final int LASERON_FIELD_NUMBER = 5;
    private boolean laserOn_;
    public boolean hasLaserOn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getLaserOn() {
      return laserOn_;
    }
    
    // optional bool roverDetected = 6;
    public static final int ROVERDETECTED_FIELD_NUMBER = 6;
    private boolean roverDetected_;
    public boolean hasRoverDetected() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getRoverDetected() {
      return roverDetected_;
    }
    
    private void initFields() {
      time_ = 0L;
      status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
      target_ = java.util.Collections.emptyList();
      laser_ = java.util.Collections.emptyList();
      laserOn_ = false;
      roverDetected_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      for (int i = 0; i < target_.size(); i++) {
        output.writeMessage(3, target_.get(i));
      }
      for (int i = 0; i < laser_.size(); i++) {
        output.writeMessage(4, laser_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(5, laserOn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(6, roverDetected_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      for (int i = 0; i < target_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, target_.get(i));
      }
      for (int i = 0; i < laser_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, laser_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, laserOn_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, roverDetected_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraTracks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cameraMsgs.CameraMsgs.cameraTracks prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cameraMsgs.CameraMsgs.cameraTracksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraTracks_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraTracks_fieldAccessorTable;
      }
      
      // Construct using cameraMsgs.CameraMsgs.cameraTracks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTargetFieldBuilder();
          getLaserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (targetBuilder_ == null) {
          target_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          targetBuilder_.clear();
        }
        if (laserBuilder_ == null) {
          laser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          laserBuilder_.clear();
        }
        laserOn_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        roverDetected_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cameraMsgs.CameraMsgs.cameraTracks.getDescriptor();
      }
      
      public cameraMsgs.CameraMsgs.cameraTracks getDefaultInstanceForType() {
        return cameraMsgs.CameraMsgs.cameraTracks.getDefaultInstance();
      }
      
      public cameraMsgs.CameraMsgs.cameraTracks build() {
        cameraMsgs.CameraMsgs.cameraTracks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cameraMsgs.CameraMsgs.cameraTracks buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cameraMsgs.CameraMsgs.cameraTracks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cameraMsgs.CameraMsgs.cameraTracks buildPartial() {
        cameraMsgs.CameraMsgs.cameraTracks result = new cameraMsgs.CameraMsgs.cameraTracks(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (targetBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            target_ = java.util.Collections.unmodifiableList(target_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        if (laserBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            laser_ = java.util.Collections.unmodifiableList(laser_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.laser_ = laser_;
        } else {
          result.laser_ = laserBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        result.laserOn_ = laserOn_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roverDetected_ = roverDetected_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cameraMsgs.CameraMsgs.cameraTracks) {
          return mergeFrom((cameraMsgs.CameraMsgs.cameraTracks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cameraMsgs.CameraMsgs.cameraTracks other) {
        if (other == cameraMsgs.CameraMsgs.cameraTracks.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (targetBuilder_ == null) {
          if (!other.target_.isEmpty()) {
            if (target_.isEmpty()) {
              target_ = other.target_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTargetIsMutable();
              target_.addAll(other.target_);
            }
            onChanged();
          }
        } else {
          if (!other.target_.isEmpty()) {
            if (targetBuilder_.isEmpty()) {
              targetBuilder_.dispose();
              targetBuilder_ = null;
              target_ = other.target_;
              bitField0_ = (bitField0_ & ~0x00000004);
              targetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTargetFieldBuilder() : null;
            } else {
              targetBuilder_.addAllMessages(other.target_);
            }
          }
        }
        if (laserBuilder_ == null) {
          if (!other.laser_.isEmpty()) {
            if (laser_.isEmpty()) {
              laser_ = other.laser_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLaserIsMutable();
              laser_.addAll(other.laser_);
            }
            onChanged();
          }
        } else {
          if (!other.laser_.isEmpty()) {
            if (laserBuilder_.isEmpty()) {
              laserBuilder_.dispose();
              laserBuilder_ = null;
              laser_ = other.laser_;
              bitField0_ = (bitField0_ & ~0x00000008);
              laserBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLaserFieldBuilder() : null;
            } else {
              laserBuilder_.addAllMessages(other.laser_);
            }
          }
        }
        if (other.hasLaserOn()) {
          setLaserOn(other.getLaserOn());
        }
        if (other.hasRoverDetected()) {
          setRoverDetected(other.getRoverDetected());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cameraMsgs.CameraMsgs.systemStatus value = cameraMsgs.CameraMsgs.systemStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              cameraMsgs.CameraMsgs.track.Builder subBuilder = cameraMsgs.CameraMsgs.track.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTarget(subBuilder.buildPartial());
              break;
            }
            case 34: {
              cameraMsgs.CameraMsgs.track.Builder subBuilder = cameraMsgs.CameraMsgs.track.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLaser(subBuilder.buildPartial());
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              laserOn_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              roverDetected_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .cameraMsgs.systemStatus status = 2 [default = UNKNOWN];
      private cameraMsgs.CameraMsgs.systemStatus status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public cameraMsgs.CameraMsgs.systemStatus getStatus() {
        return status_;
      }
      public Builder setStatus(cameraMsgs.CameraMsgs.systemStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = cameraMsgs.CameraMsgs.systemStatus.UNKNOWN;
        onChanged();
        return this;
      }
      
      // repeated .cameraMsgs.track target = 3;
      private java.util.List<cameraMsgs.CameraMsgs.track> target_ =
        java.util.Collections.emptyList();
      private void ensureTargetIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          target_ = new java.util.ArrayList<cameraMsgs.CameraMsgs.track>(target_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder> targetBuilder_;
      
      public java.util.List<cameraMsgs.CameraMsgs.track> getTargetList() {
        if (targetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(target_);
        } else {
          return targetBuilder_.getMessageList();
        }
      }
      public int getTargetCount() {
        if (targetBuilder_ == null) {
          return target_.size();
        } else {
          return targetBuilder_.getCount();
        }
      }
      public cameraMsgs.CameraMsgs.track getTarget(int index) {
        if (targetBuilder_ == null) {
          return target_.get(index);
        } else {
          return targetBuilder_.getMessage(index);
        }
      }
      public Builder setTarget(
          int index, cameraMsgs.CameraMsgs.track value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetIsMutable();
          target_.set(index, value);
          onChanged();
        } else {
          targetBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTarget(
          int index, cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (targetBuilder_ == null) {
          ensureTargetIsMutable();
          target_.set(index, builderForValue.build());
          onChanged();
        } else {
          targetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTarget(cameraMsgs.CameraMsgs.track value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetIsMutable();
          target_.add(value);
          onChanged();
        } else {
          targetBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTarget(
          int index, cameraMsgs.CameraMsgs.track value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetIsMutable();
          target_.add(index, value);
          onChanged();
        } else {
          targetBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTarget(
          cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (targetBuilder_ == null) {
          ensureTargetIsMutable();
          target_.add(builderForValue.build());
          onChanged();
        } else {
          targetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTarget(
          int index, cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (targetBuilder_ == null) {
          ensureTargetIsMutable();
          target_.add(index, builderForValue.build());
          onChanged();
        } else {
          targetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTarget(
          java.lang.Iterable<? extends cameraMsgs.CameraMsgs.track> values) {
        if (targetBuilder_ == null) {
          ensureTargetIsMutable();
          super.addAll(values, target_);
          onChanged();
        } else {
          targetBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          targetBuilder_.clear();
        }
        return this;
      }
      public Builder removeTarget(int index) {
        if (targetBuilder_ == null) {
          ensureTargetIsMutable();
          target_.remove(index);
          onChanged();
        } else {
          targetBuilder_.remove(index);
        }
        return this;
      }
      public cameraMsgs.CameraMsgs.track.Builder getTargetBuilder(
          int index) {
        return getTargetFieldBuilder().getBuilder(index);
      }
      public cameraMsgs.CameraMsgs.trackOrBuilder getTargetOrBuilder(
          int index) {
        if (targetBuilder_ == null) {
          return target_.get(index);  } else {
          return targetBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
           getTargetOrBuilderList() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(target_);
        }
      }
      public cameraMsgs.CameraMsgs.track.Builder addTargetBuilder() {
        return getTargetFieldBuilder().addBuilder(
            cameraMsgs.CameraMsgs.track.getDefaultInstance());
      }
      public cameraMsgs.CameraMsgs.track.Builder addTargetBuilder(
          int index) {
        return getTargetFieldBuilder().addBuilder(
            index, cameraMsgs.CameraMsgs.track.getDefaultInstance());
      }
      public java.util.List<cameraMsgs.CameraMsgs.track.Builder> 
           getTargetBuilderList() {
        return getTargetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder>(
                  target_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }
      
      // repeated .cameraMsgs.track laser = 4;
      private java.util.List<cameraMsgs.CameraMsgs.track> laser_ =
        java.util.Collections.emptyList();
      private void ensureLaserIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          laser_ = new java.util.ArrayList<cameraMsgs.CameraMsgs.track>(laser_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder> laserBuilder_;
      
      public java.util.List<cameraMsgs.CameraMsgs.track> getLaserList() {
        if (laserBuilder_ == null) {
          return java.util.Collections.unmodifiableList(laser_);
        } else {
          return laserBuilder_.getMessageList();
        }
      }
      public int getLaserCount() {
        if (laserBuilder_ == null) {
          return laser_.size();
        } else {
          return laserBuilder_.getCount();
        }
      }
      public cameraMsgs.CameraMsgs.track getLaser(int index) {
        if (laserBuilder_ == null) {
          return laser_.get(index);
        } else {
          return laserBuilder_.getMessage(index);
        }
      }
      public Builder setLaser(
          int index, cameraMsgs.CameraMsgs.track value) {
        if (laserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLaserIsMutable();
          laser_.set(index, value);
          onChanged();
        } else {
          laserBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLaser(
          int index, cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (laserBuilder_ == null) {
          ensureLaserIsMutable();
          laser_.set(index, builderForValue.build());
          onChanged();
        } else {
          laserBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLaser(cameraMsgs.CameraMsgs.track value) {
        if (laserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLaserIsMutable();
          laser_.add(value);
          onChanged();
        } else {
          laserBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLaser(
          int index, cameraMsgs.CameraMsgs.track value) {
        if (laserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLaserIsMutable();
          laser_.add(index, value);
          onChanged();
        } else {
          laserBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLaser(
          cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (laserBuilder_ == null) {
          ensureLaserIsMutable();
          laser_.add(builderForValue.build());
          onChanged();
        } else {
          laserBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLaser(
          int index, cameraMsgs.CameraMsgs.track.Builder builderForValue) {
        if (laserBuilder_ == null) {
          ensureLaserIsMutable();
          laser_.add(index, builderForValue.build());
          onChanged();
        } else {
          laserBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLaser(
          java.lang.Iterable<? extends cameraMsgs.CameraMsgs.track> values) {
        if (laserBuilder_ == null) {
          ensureLaserIsMutable();
          super.addAll(values, laser_);
          onChanged();
        } else {
          laserBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLaser() {
        if (laserBuilder_ == null) {
          laser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          laserBuilder_.clear();
        }
        return this;
      }
      public Builder removeLaser(int index) {
        if (laserBuilder_ == null) {
          ensureLaserIsMutable();
          laser_.remove(index);
          onChanged();
        } else {
          laserBuilder_.remove(index);
        }
        return this;
      }
      public cameraMsgs.CameraMsgs.track.Builder getLaserBuilder(
          int index) {
        return getLaserFieldBuilder().getBuilder(index);
      }
      public cameraMsgs.CameraMsgs.trackOrBuilder getLaserOrBuilder(
          int index) {
        if (laserBuilder_ == null) {
          return laser_.get(index);  } else {
          return laserBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends cameraMsgs.CameraMsgs.trackOrBuilder> 
           getLaserOrBuilderList() {
        if (laserBuilder_ != null) {
          return laserBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(laser_);
        }
      }
      public cameraMsgs.CameraMsgs.track.Builder addLaserBuilder() {
        return getLaserFieldBuilder().addBuilder(
            cameraMsgs.CameraMsgs.track.getDefaultInstance());
      }
      public cameraMsgs.CameraMsgs.track.Builder addLaserBuilder(
          int index) {
        return getLaserFieldBuilder().addBuilder(
            index, cameraMsgs.CameraMsgs.track.getDefaultInstance());
      }
      public java.util.List<cameraMsgs.CameraMsgs.track.Builder> 
           getLaserBuilderList() {
        return getLaserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder> 
          getLaserFieldBuilder() {
        if (laserBuilder_ == null) {
          laserBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cameraMsgs.CameraMsgs.track, cameraMsgs.CameraMsgs.track.Builder, cameraMsgs.CameraMsgs.trackOrBuilder>(
                  laser_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          laser_ = null;
        }
        return laserBuilder_;
      }
      
      // optional bool laserOn = 5;
      private boolean laserOn_ ;
      public boolean hasLaserOn() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getLaserOn() {
        return laserOn_;
      }
      public Builder setLaserOn(boolean value) {
        bitField0_ |= 0x00000010;
        laserOn_ = value;
        onChanged();
        return this;
      }
      public Builder clearLaserOn() {
        bitField0_ = (bitField0_ & ~0x00000010);
        laserOn_ = false;
        onChanged();
        return this;
      }
      
      // optional bool roverDetected = 6;
      private boolean roverDetected_ ;
      public boolean hasRoverDetected() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getRoverDetected() {
        return roverDetected_;
      }
      public Builder setRoverDetected(boolean value) {
        bitField0_ |= 0x00000020;
        roverDetected_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoverDetected() {
        bitField0_ = (bitField0_ & ~0x00000020);
        roverDetected_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cameraMsgs.cameraTracks)
    }
    
    static {
      defaultInstance = new cameraTracks(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cameraMsgs.cameraTracks)
  }
  
  public interface cameraImageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // optional sint32 channels = 2;
    boolean hasChannels();
    int getChannels();
    
    // optional sint32 sizeX = 3;
    boolean hasSizeX();
    int getSizeX();
    
    // optional sint32 sizeY = 4;
    boolean hasSizeY();
    int getSizeY();
    
    // optional bytes imageData = 5;
    boolean hasImageData();
    com.google.protobuf.ByteString getImageData();
  }
  public static final class cameraImage extends
      com.google.protobuf.GeneratedMessage
      implements cameraImageOrBuilder {
    // Use cameraImage.newBuilder() to construct.
    private cameraImage(Builder builder) {
      super(builder);
    }
    private cameraImage(boolean noInit) {}
    
    private static final cameraImage defaultInstance;
    public static cameraImage getDefaultInstance() {
      return defaultInstance;
    }
    
    public cameraImage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraImage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraImage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // optional sint32 channels = 2;
    public static final int CHANNELS_FIELD_NUMBER = 2;
    private int channels_;
    public boolean hasChannels() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getChannels() {
      return channels_;
    }
    
    // optional sint32 sizeX = 3;
    public static final int SIZEX_FIELD_NUMBER = 3;
    private int sizeX_;
    public boolean hasSizeX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSizeX() {
      return sizeX_;
    }
    
    // optional sint32 sizeY = 4;
    public static final int SIZEY_FIELD_NUMBER = 4;
    private int sizeY_;
    public boolean hasSizeY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSizeY() {
      return sizeY_;
    }
    
    // optional bytes imageData = 5;
    public static final int IMAGEDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString imageData_;
    public boolean hasImageData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }
    
    private void initFields() {
      time_ = 0L;
      channels_ = 0;
      sizeX_ = 0;
      sizeY_ = 0;
      imageData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt32(2, channels_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, sizeX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, sizeY_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, imageData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, channels_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, sizeX_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, sizeY_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, imageData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cameraMsgs.CameraMsgs.cameraImage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cameraMsgs.CameraMsgs.cameraImage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cameraMsgs.CameraMsgs.cameraImageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraImage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cameraMsgs.CameraMsgs.internal_static_cameraMsgs_cameraImage_fieldAccessorTable;
      }
      
      // Construct using cameraMsgs.CameraMsgs.cameraImage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        channels_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sizeX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sizeY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        imageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cameraMsgs.CameraMsgs.cameraImage.getDescriptor();
      }
      
      public cameraMsgs.CameraMsgs.cameraImage getDefaultInstanceForType() {
        return cameraMsgs.CameraMsgs.cameraImage.getDefaultInstance();
      }
      
      public cameraMsgs.CameraMsgs.cameraImage build() {
        cameraMsgs.CameraMsgs.cameraImage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cameraMsgs.CameraMsgs.cameraImage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cameraMsgs.CameraMsgs.cameraImage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cameraMsgs.CameraMsgs.cameraImage buildPartial() {
        cameraMsgs.CameraMsgs.cameraImage result = new cameraMsgs.CameraMsgs.cameraImage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channels_ = channels_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sizeX_ = sizeX_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sizeY_ = sizeY_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.imageData_ = imageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cameraMsgs.CameraMsgs.cameraImage) {
          return mergeFrom((cameraMsgs.CameraMsgs.cameraImage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cameraMsgs.CameraMsgs.cameraImage other) {
        if (other == cameraMsgs.CameraMsgs.cameraImage.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasChannels()) {
          setChannels(other.getChannels());
        }
        if (other.hasSizeX()) {
          setSizeX(other.getSizeX());
        }
        if (other.hasSizeY()) {
          setSizeY(other.getSizeY());
        }
        if (other.hasImageData()) {
          setImageData(other.getImageData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channels_ = input.readSInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sizeX_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sizeY_ = input.readSInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              imageData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional sint32 channels = 2;
      private int channels_ ;
      public boolean hasChannels() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getChannels() {
        return channels_;
      }
      public Builder setChannels(int value) {
        bitField0_ |= 0x00000002;
        channels_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannels() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channels_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 sizeX = 3;
      private int sizeX_ ;
      public boolean hasSizeX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSizeX() {
        return sizeX_;
      }
      public Builder setSizeX(int value) {
        bitField0_ |= 0x00000004;
        sizeX_ = value;
        onChanged();
        return this;
      }
      public Builder clearSizeX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sizeX_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 sizeY = 4;
      private int sizeY_ ;
      public boolean hasSizeY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSizeY() {
        return sizeY_;
      }
      public Builder setSizeY(int value) {
        bitField0_ |= 0x00000008;
        sizeY_ = value;
        onChanged();
        return this;
      }
      public Builder clearSizeY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sizeY_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes imageData = 5;
      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasImageData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        imageData_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cameraMsgs.cameraImage)
    }
    
    static {
      defaultInstance = new cameraImage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cameraMsgs.cameraImage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cameraMsgs_cameraStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cameraMsgs_cameraStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cameraMsgs_track_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cameraMsgs_track_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cameraMsgs_cameraTracks_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cameraMsgs_cameraTracks_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cameraMsgs_cameraImage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cameraMsgs_cameraImage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020cameraMsgs.proto\022\ncameraMsgs\"n\n\014camera" +
      "Status\022\014\n\004time\030\001 \001(\003\0221\n\006status\030\002 \001(\0162\030.c" +
      "ameraMsgs.systemStatus:\007UNKNOWN\022\017\n\007laser" +
      "On\030\003 \001(\010\022\014\n\004text\030\004 \001(\t\"\035\n\005track\022\t\n\001x\030\001 \001" +
      "(\021\022\t\n\001y\030\002 \001(\021\"\274\001\n\014cameraTracks\022\014\n\004time\030\001" +
      " \001(\003\0221\n\006status\030\002 \001(\0162\030.cameraMsgs.system" +
      "Status:\007UNKNOWN\022!\n\006target\030\003 \003(\0132\021.camera" +
      "Msgs.track\022 \n\005laser\030\004 \003(\0132\021.cameraMsgs.t" +
      "rack\022\017\n\007laserOn\030\005 \001(\010\022\025\n\rroverDetected\030\006" +
      " \001(\010\"^\n\013cameraImage\022\014\n\004time\030\001 \001(\003\022\020\n\010cha",
      "nnels\030\002 \001(\021\022\r\n\005sizeX\030\003 \001(\021\022\r\n\005sizeY\030\004 \001(" +
      "\021\022\021\n\timageData\030\005 \001(\014*{\n\014systemStatus\022\017\n\013" +
      "CAMERA_DOWN\020\000\022\020\n\014CAMERA_READY\020\001\022\026\n\022CAMER" +
      "A_OPERATIONAL\020\002\022\020\n\014CAMERA_ERROR\020\003\022\021\n\rCAM" +
      "ERA_FAILED\020\004\022\013\n\007UNKNOWN\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cameraMsgs_cameraStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cameraMsgs_cameraStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cameraMsgs_cameraStatus_descriptor,
              new java.lang.String[] { "Time", "Status", "LaserOn", "Text", },
              cameraMsgs.CameraMsgs.cameraStatus.class,
              cameraMsgs.CameraMsgs.cameraStatus.Builder.class);
          internal_static_cameraMsgs_track_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cameraMsgs_track_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cameraMsgs_track_descriptor,
              new java.lang.String[] { "X", "Y", },
              cameraMsgs.CameraMsgs.track.class,
              cameraMsgs.CameraMsgs.track.Builder.class);
          internal_static_cameraMsgs_cameraTracks_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_cameraMsgs_cameraTracks_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cameraMsgs_cameraTracks_descriptor,
              new java.lang.String[] { "Time", "Status", "Target", "Laser", "LaserOn", "RoverDetected", },
              cameraMsgs.CameraMsgs.cameraTracks.class,
              cameraMsgs.CameraMsgs.cameraTracks.Builder.class);
          internal_static_cameraMsgs_cameraImage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_cameraMsgs_cameraImage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cameraMsgs_cameraImage_descriptor,
              new java.lang.String[] { "Time", "Channels", "SizeX", "SizeY", "ImageData", },
              cameraMsgs.CameraMsgs.cameraImage.class,
              cameraMsgs.CameraMsgs.cameraImage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
