# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='cameraMsgs.proto',
  package='cameraMsgs',
  serialized_pb='\n\x10\x63\x61meraMsgs.proto\x12\ncameraMsgs\"n\n\x0c\x63\x61meraStatus\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x31\n\x06status\x18\x02 \x01(\x0e\x32\x18.cameraMsgs.systemStatus:\x07UNKNOWN\x12\x0f\n\x07laserOn\x18\x03 \x01(\x08\x12\x0c\n\x04text\x18\x04 \x01(\t\"\x1d\n\x05track\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\"\xbc\x01\n\x0c\x63\x61meraTracks\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x31\n\x06status\x18\x02 \x01(\x0e\x32\x18.cameraMsgs.systemStatus:\x07UNKNOWN\x12!\n\x06target\x18\x03 \x03(\x0b\x32\x11.cameraMsgs.track\x12 \n\x05laser\x18\x04 \x03(\x0b\x32\x11.cameraMsgs.track\x12\x0f\n\x07laserOn\x18\x05 \x01(\x08\x12\x15\n\rroverDetected\x18\x06 \x01(\x08\"^\n\x0b\x63\x61meraImage\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x11\x12\r\n\x05sizeX\x18\x03 \x01(\x11\x12\r\n\x05sizeY\x18\x04 \x01(\x11\x12\x11\n\timageData\x18\x05 \x01(\x0c*{\n\x0csystemStatus\x12\x0f\n\x0b\x43\x41MERA_DOWN\x10\x00\x12\x10\n\x0c\x43\x41MERA_READY\x10\x01\x12\x16\n\x12\x43\x41MERA_OPERATIONAL\x10\x02\x12\x10\n\x0c\x43\x41MERA_ERROR\x10\x03\x12\x11\n\rCAMERA_FAILED\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05')

_SYSTEMSTATUS = descriptor.EnumDescriptor(
  name='systemStatus',
  full_name='cameraMsgs.systemStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CAMERA_DOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAMERA_READY', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAMERA_OPERATIONAL', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAMERA_ERROR', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAMERA_FAILED', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=462,
  serialized_end=585,
)


CAMERA_DOWN = 0
CAMERA_READY = 1
CAMERA_OPERATIONAL = 2
CAMERA_ERROR = 3
CAMERA_FAILED = 4
UNKNOWN = 5



_CAMERASTATUS = descriptor.Descriptor(
  name='cameraStatus',
  full_name='cameraMsgs.cameraStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='cameraMsgs.cameraStatus.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='cameraMsgs.cameraStatus.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='laserOn', full_name='cameraMsgs.cameraStatus.laserOn', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='cameraMsgs.cameraStatus.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=142,
)


_TRACK = descriptor.Descriptor(
  name='track',
  full_name='cameraMsgs.track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='cameraMsgs.track.x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='cameraMsgs.track.y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=173,
)


_CAMERATRACKS = descriptor.Descriptor(
  name='cameraTracks',
  full_name='cameraMsgs.cameraTracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='cameraMsgs.cameraTracks.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='cameraMsgs.cameraTracks.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='cameraMsgs.cameraTracks.target', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='laser', full_name='cameraMsgs.cameraTracks.laser', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='laserOn', full_name='cameraMsgs.cameraTracks.laserOn', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roverDetected', full_name='cameraMsgs.cameraTracks.roverDetected', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=176,
  serialized_end=364,
)


_CAMERAIMAGE = descriptor.Descriptor(
  name='cameraImage',
  full_name='cameraMsgs.cameraImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='time', full_name='cameraMsgs.cameraImage.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channels', full_name='cameraMsgs.cameraImage.channels', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sizeX', full_name='cameraMsgs.cameraImage.sizeX', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sizeY', full_name='cameraMsgs.cameraImage.sizeY', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imageData', full_name='cameraMsgs.cameraImage.imageData', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=366,
  serialized_end=460,
)

_CAMERASTATUS.fields_by_name['status'].enum_type = _SYSTEMSTATUS
_CAMERATRACKS.fields_by_name['status'].enum_type = _SYSTEMSTATUS
_CAMERATRACKS.fields_by_name['target'].message_type = _TRACK
_CAMERATRACKS.fields_by_name['laser'].message_type = _TRACK
DESCRIPTOR.message_types_by_name['cameraStatus'] = _CAMERASTATUS
DESCRIPTOR.message_types_by_name['track'] = _TRACK
DESCRIPTOR.message_types_by_name['cameraTracks'] = _CAMERATRACKS
DESCRIPTOR.message_types_by_name['cameraImage'] = _CAMERAIMAGE

class cameraStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMERASTATUS
  
  # @@protoc_insertion_point(class_scope:cameraMsgs.cameraStatus)

class track(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACK
  
  # @@protoc_insertion_point(class_scope:cameraMsgs.track)

class cameraTracks(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMERATRACKS
  
  # @@protoc_insertion_point(class_scope:cameraMsgs.cameraTracks)

class cameraImage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMERAIMAGE
  
  # @@protoc_insertion_point(class_scope:cameraMsgs.cameraImage)

# @@protoc_insertion_point(module_scope)
