// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laserMsgs.proto

package laserMsgs;

public final class LaserMsgs {
  private LaserMsgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum systemStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    LASER_DOWN(0, 0),
    LASER_READY(1, 1),
    LASER_OPERATIONAL(2, 2),
    LASER_ERROR(3, 3),
    LASER_FAILED(4, 4),
    UNKNOWN(5, 5),
    ;
    
    public static final int LASER_DOWN_VALUE = 0;
    public static final int LASER_READY_VALUE = 1;
    public static final int LASER_OPERATIONAL_VALUE = 2;
    public static final int LASER_ERROR_VALUE = 3;
    public static final int LASER_FAILED_VALUE = 4;
    public static final int UNKNOWN_VALUE = 5;
    
    
    public final int getNumber() { return value; }
    
    public static systemStatus valueOf(int value) {
      switch (value) {
        case 0: return LASER_DOWN;
        case 1: return LASER_READY;
        case 2: return LASER_OPERATIONAL;
        case 3: return LASER_ERROR;
        case 4: return LASER_FAILED;
        case 5: return UNKNOWN;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<systemStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<systemStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<systemStatus>() {
            public systemStatus findValueByNumber(int number) {
              return systemStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return laserMsgs.LaserMsgs.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final systemStatus[] VALUES = {
      LASER_DOWN, LASER_READY, LASER_OPERATIONAL, LASER_ERROR, LASER_FAILED, UNKNOWN, 
    };
    
    public static systemStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private systemStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:laserMsgs.systemStatus)
  }
  
  public interface laserStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // optional .laserMsgs.systemStatus status = 2 [default = UNKNOWN];
    boolean hasStatus();
    laserMsgs.LaserMsgs.systemStatus getStatus();
    
    // optional string text = 3;
    boolean hasText();
    String getText();
  }
  public static final class laserStatus extends
      com.google.protobuf.GeneratedMessage
      implements laserStatusOrBuilder {
    // Use laserStatus.newBuilder() to construct.
    private laserStatus(Builder builder) {
      super(builder);
    }
    private laserStatus(boolean noInit) {}
    
    private static final laserStatus defaultInstance;
    public static laserStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public laserStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserStatus_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // optional .laserMsgs.systemStatus status = 2 [default = UNKNOWN];
    public static final int STATUS_FIELD_NUMBER = 2;
    private laserMsgs.LaserMsgs.systemStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public laserMsgs.LaserMsgs.systemStatus getStatus() {
      return status_;
    }
    
    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      time_ = 0L;
      status_ = laserMsgs.LaserMsgs.systemStatus.UNKNOWN;
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.laserStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(laserMsgs.LaserMsgs.laserStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements laserMsgs.LaserMsgs.laserStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserStatus_fieldAccessorTable;
      }
      
      // Construct using laserMsgs.LaserMsgs.laserStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = laserMsgs.LaserMsgs.systemStatus.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return laserMsgs.LaserMsgs.laserStatus.getDescriptor();
      }
      
      public laserMsgs.LaserMsgs.laserStatus getDefaultInstanceForType() {
        return laserMsgs.LaserMsgs.laserStatus.getDefaultInstance();
      }
      
      public laserMsgs.LaserMsgs.laserStatus build() {
        laserMsgs.LaserMsgs.laserStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private laserMsgs.LaserMsgs.laserStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        laserMsgs.LaserMsgs.laserStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public laserMsgs.LaserMsgs.laserStatus buildPartial() {
        laserMsgs.LaserMsgs.laserStatus result = new laserMsgs.LaserMsgs.laserStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof laserMsgs.LaserMsgs.laserStatus) {
          return mergeFrom((laserMsgs.LaserMsgs.laserStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(laserMsgs.LaserMsgs.laserStatus other) {
        if (other == laserMsgs.LaserMsgs.laserStatus.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              laserMsgs.LaserMsgs.systemStatus value = laserMsgs.LaserMsgs.systemStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .laserMsgs.systemStatus status = 2 [default = UNKNOWN];
      private laserMsgs.LaserMsgs.systemStatus status_ = laserMsgs.LaserMsgs.systemStatus.UNKNOWN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public laserMsgs.LaserMsgs.systemStatus getStatus() {
        return status_;
      }
      public Builder setStatus(laserMsgs.LaserMsgs.systemStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = laserMsgs.LaserMsgs.systemStatus.UNKNOWN;
        onChanged();
        return this;
      }
      
      // optional string text = 3;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:laserMsgs.laserStatus)
    }
    
    static {
      defaultInstance = new laserStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:laserMsgs.laserStatus)
  }
  
  public interface poseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 pulseAZ = 1;
    boolean hasPulseAZ();
    int getPulseAZ();
    
    // optional uint32 pulseEL = 2;
    boolean hasPulseEL();
    int getPulseEL();
  }
  public static final class pose extends
      com.google.protobuf.GeneratedMessage
      implements poseOrBuilder {
    // Use pose.newBuilder() to construct.
    private pose(Builder builder) {
      super(builder);
    }
    private pose(boolean noInit) {}
    
    private static final pose defaultInstance;
    public static pose getDefaultInstance() {
      return defaultInstance;
    }
    
    public pose getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_pose_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_pose_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 pulseAZ = 1;
    public static final int PULSEAZ_FIELD_NUMBER = 1;
    private int pulseAZ_;
    public boolean hasPulseAZ() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPulseAZ() {
      return pulseAZ_;
    }
    
    // optional uint32 pulseEL = 2;
    public static final int PULSEEL_FIELD_NUMBER = 2;
    private int pulseEL_;
    public boolean hasPulseEL() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPulseEL() {
      return pulseEL_;
    }
    
    private void initFields() {
      pulseAZ_ = 0;
      pulseEL_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, pulseAZ_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, pulseEL_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, pulseAZ_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, pulseEL_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static laserMsgs.LaserMsgs.pose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.pose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.pose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(laserMsgs.LaserMsgs.pose prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements laserMsgs.LaserMsgs.poseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_pose_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_pose_fieldAccessorTable;
      }
      
      // Construct using laserMsgs.LaserMsgs.pose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pulseAZ_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pulseEL_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return laserMsgs.LaserMsgs.pose.getDescriptor();
      }
      
      public laserMsgs.LaserMsgs.pose getDefaultInstanceForType() {
        return laserMsgs.LaserMsgs.pose.getDefaultInstance();
      }
      
      public laserMsgs.LaserMsgs.pose build() {
        laserMsgs.LaserMsgs.pose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private laserMsgs.LaserMsgs.pose buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        laserMsgs.LaserMsgs.pose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public laserMsgs.LaserMsgs.pose buildPartial() {
        laserMsgs.LaserMsgs.pose result = new laserMsgs.LaserMsgs.pose(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pulseAZ_ = pulseAZ_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pulseEL_ = pulseEL_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof laserMsgs.LaserMsgs.pose) {
          return mergeFrom((laserMsgs.LaserMsgs.pose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(laserMsgs.LaserMsgs.pose other) {
        if (other == laserMsgs.LaserMsgs.pose.getDefaultInstance()) return this;
        if (other.hasPulseAZ()) {
          setPulseAZ(other.getPulseAZ());
        }
        if (other.hasPulseEL()) {
          setPulseEL(other.getPulseEL());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pulseAZ_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pulseEL_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 pulseAZ = 1;
      private int pulseAZ_ ;
      public boolean hasPulseAZ() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPulseAZ() {
        return pulseAZ_;
      }
      public Builder setPulseAZ(int value) {
        bitField0_ |= 0x00000001;
        pulseAZ_ = value;
        onChanged();
        return this;
      }
      public Builder clearPulseAZ() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pulseAZ_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 pulseEL = 2;
      private int pulseEL_ ;
      public boolean hasPulseEL() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPulseEL() {
        return pulseEL_;
      }
      public Builder setPulseEL(int value) {
        bitField0_ |= 0x00000002;
        pulseEL_ = value;
        onChanged();
        return this;
      }
      public Builder clearPulseEL() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pulseEL_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:laserMsgs.pose)
    }
    
    static {
      defaultInstance = new pose(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:laserMsgs.pose)
  }
  
  public interface laserPoseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 time = 1;
    boolean hasTime();
    long getTime();
    
    // optional .laserMsgs.pose target = 2;
    boolean hasTarget();
    laserMsgs.LaserMsgs.pose getTarget();
    laserMsgs.LaserMsgs.poseOrBuilder getTargetOrBuilder();
    
    // optional bool laserOn = 3;
    boolean hasLaserOn();
    boolean getLaserOn();
  }
  public static final class laserPose extends
      com.google.protobuf.GeneratedMessage
      implements laserPoseOrBuilder {
    // Use laserPose.newBuilder() to construct.
    private laserPose(Builder builder) {
      super(builder);
    }
    private laserPose(boolean noInit) {}
    
    private static final laserPose defaultInstance;
    public static laserPose getDefaultInstance() {
      return defaultInstance;
    }
    
    public laserPose getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserPose_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserPose_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTime() {
      return time_;
    }
    
    // optional .laserMsgs.pose target = 2;
    public static final int TARGET_FIELD_NUMBER = 2;
    private laserMsgs.LaserMsgs.pose target_;
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public laserMsgs.LaserMsgs.pose getTarget() {
      return target_;
    }
    public laserMsgs.LaserMsgs.poseOrBuilder getTargetOrBuilder() {
      return target_;
    }
    
    // optional bool laserOn = 3;
    public static final int LASERON_FIELD_NUMBER = 3;
    private boolean laserOn_;
    public boolean hasLaserOn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getLaserOn() {
      return laserOn_;
    }
    
    private void initFields() {
      time_ = 0L;
      target_ = laserMsgs.LaserMsgs.pose.getDefaultInstance();
      laserOn_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, target_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, laserOn_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, target_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, laserOn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.laserPose parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static laserMsgs.LaserMsgs.laserPose parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(laserMsgs.LaserMsgs.laserPose prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements laserMsgs.LaserMsgs.laserPoseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserPose_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return laserMsgs.LaserMsgs.internal_static_laserMsgs_laserPose_fieldAccessorTable;
      }
      
      // Construct using laserMsgs.LaserMsgs.laserPose.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTargetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (targetBuilder_ == null) {
          target_ = laserMsgs.LaserMsgs.pose.getDefaultInstance();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        laserOn_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return laserMsgs.LaserMsgs.laserPose.getDescriptor();
      }
      
      public laserMsgs.LaserMsgs.laserPose getDefaultInstanceForType() {
        return laserMsgs.LaserMsgs.laserPose.getDefaultInstance();
      }
      
      public laserMsgs.LaserMsgs.laserPose build() {
        laserMsgs.LaserMsgs.laserPose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private laserMsgs.LaserMsgs.laserPose buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        laserMsgs.LaserMsgs.laserPose result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public laserMsgs.LaserMsgs.laserPose buildPartial() {
        laserMsgs.LaserMsgs.laserPose result = new laserMsgs.LaserMsgs.laserPose(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (targetBuilder_ == null) {
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.laserOn_ = laserOn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof laserMsgs.LaserMsgs.laserPose) {
          return mergeFrom((laserMsgs.LaserMsgs.laserPose)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(laserMsgs.LaserMsgs.laserPose other) {
        if (other == laserMsgs.LaserMsgs.laserPose.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        if (other.hasLaserOn()) {
          setLaserOn(other.getLaserOn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
            case 18: {
              laserMsgs.LaserMsgs.pose.Builder subBuilder = laserMsgs.LaserMsgs.pose.newBuilder();
              if (hasTarget()) {
                subBuilder.mergeFrom(getTarget());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTarget(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              laserOn_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 time = 1;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .laserMsgs.pose target = 2;
      private laserMsgs.LaserMsgs.pose target_ = laserMsgs.LaserMsgs.pose.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          laserMsgs.LaserMsgs.pose, laserMsgs.LaserMsgs.pose.Builder, laserMsgs.LaserMsgs.poseOrBuilder> targetBuilder_;
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public laserMsgs.LaserMsgs.pose getTarget() {
        if (targetBuilder_ == null) {
          return target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      public Builder setTarget(laserMsgs.LaserMsgs.pose value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
          onChanged();
        } else {
          targetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setTarget(
          laserMsgs.LaserMsgs.pose.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
          onChanged();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeTarget(laserMsgs.LaserMsgs.pose value) {
        if (targetBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              target_ != laserMsgs.LaserMsgs.pose.getDefaultInstance()) {
            target_ =
              laserMsgs.LaserMsgs.pose.newBuilder(target_).mergeFrom(value).buildPartial();
          } else {
            target_ = value;
          }
          onChanged();
        } else {
          targetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = laserMsgs.LaserMsgs.pose.getDefaultInstance();
          onChanged();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public laserMsgs.LaserMsgs.pose.Builder getTargetBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      public laserMsgs.LaserMsgs.poseOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          laserMsgs.LaserMsgs.pose, laserMsgs.LaserMsgs.pose.Builder, laserMsgs.LaserMsgs.poseOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              laserMsgs.LaserMsgs.pose, laserMsgs.LaserMsgs.pose.Builder, laserMsgs.LaserMsgs.poseOrBuilder>(
                  target_,
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }
      
      // optional bool laserOn = 3;
      private boolean laserOn_ ;
      public boolean hasLaserOn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getLaserOn() {
        return laserOn_;
      }
      public Builder setLaserOn(boolean value) {
        bitField0_ |= 0x00000004;
        laserOn_ = value;
        onChanged();
        return this;
      }
      public Builder clearLaserOn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        laserOn_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:laserMsgs.laserPose)
    }
    
    static {
      defaultInstance = new laserPose(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:laserMsgs.laserPose)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_laserMsgs_laserStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laserMsgs_laserStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_laserMsgs_pose_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laserMsgs_pose_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_laserMsgs_laserPose_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laserMsgs_laserPose_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017laserMsgs.proto\022\tlaserMsgs\"[\n\013laserSta" +
      "tus\022\014\n\004time\030\001 \001(\003\0220\n\006status\030\002 \001(\0162\027.lase" +
      "rMsgs.systemStatus:\007UNKNOWN\022\014\n\004text\030\003 \001(" +
      "\t\"(\n\004pose\022\017\n\007pulseAZ\030\001 \001(\r\022\017\n\007pulseEL\030\002 " +
      "\001(\r\"K\n\tlaserPose\022\014\n\004time\030\001 \001(\003\022\037\n\006target" +
      "\030\002 \001(\0132\017.laserMsgs.pose\022\017\n\007laserOn\030\003 \001(\010" +
      "*v\n\014systemStatus\022\016\n\nLASER_DOWN\020\000\022\017\n\013LASE" +
      "R_READY\020\001\022\025\n\021LASER_OPERATIONAL\020\002\022\017\n\013LASE" +
      "R_ERROR\020\003\022\020\n\014LASER_FAILED\020\004\022\013\n\007UNKNOWN\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_laserMsgs_laserStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_laserMsgs_laserStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_laserMsgs_laserStatus_descriptor,
              new java.lang.String[] { "Time", "Status", "Text", },
              laserMsgs.LaserMsgs.laserStatus.class,
              laserMsgs.LaserMsgs.laserStatus.Builder.class);
          internal_static_laserMsgs_pose_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_laserMsgs_pose_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_laserMsgs_pose_descriptor,
              new java.lang.String[] { "PulseAZ", "PulseEL", },
              laserMsgs.LaserMsgs.pose.class,
              laserMsgs.LaserMsgs.pose.Builder.class);
          internal_static_laserMsgs_laserPose_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_laserMsgs_laserPose_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_laserMsgs_laserPose_descriptor,
              new java.lang.String[] { "Time", "Target", "LaserOn", },
              laserMsgs.LaserMsgs.laserPose.class,
              laserMsgs.LaserMsgs.laserPose.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
